In [13]:
# Task 1
import pandas as pd
cat_human = pd.read_csv('cat_human.csv')
# No cleaning required

Color        0
Eye_color    0
Height       0
Legs         0
Moustache    0
Tail         0
Weight       0
label        0
dtype: int64

In [104]:
# Task 2
import numpy as np

# Dropping Coloumns
# del cat_human["Color","Eye_color","Moustache",]

# Separate features and labels
X = np.c_[cat_human.iloc[:,0:4]]
Y = cat_human.iloc[:,4]

# Vectorization
import sklearn.preprocessing as sp
encoder = sp.LabelEncoder()
Y1 = encoder.fit_transform(Y).reshape(-1,1)
X[:,0] = X[:,0]/X[:,0].max()
X[:,1] = X[:,1]/X[:,1].max()
X[:,2] = encoder.fit_transform(X[:,2])
X[:,3] = X[:,3]/X[:,3].max()



array([[0.7363896848137534, 0.5, 0, 0.8793969849246231],
       [0.9742120343839541, 0.5, 0, 0.8090452261306534],
       [0.7163323782234956, 0.5, 0, 0.8140703517587939],
       [0.8452722063037249, 0.5, 0, 0.9899497487437187],
       [0.9398280802292263, 0.5, 0, 0.9195979899497488],
       [0.7965616045845271, 0.5, 0, 0.8190954773869348],
       [0.8538681948424068, 0.5, 0, 0.834170854271357],
       [0.8710601719197707, 0.5, 0, 0.6884422110552764],
       [0.7994269340974212, 0.5, 0, 0.5979899497487438],
       [0.8681948424068767, 0.5, 0, 0.7638190954773869],
       [0.7879656160458453, 0.5, 0, 0.7135678391959799],
       [0.9598853868194842, 0.5, 0, 0.5025125628140704],
       [0.9713467048710601, 0.5, 0, 0.7788944723618091],
       [0.8108882521489971, 0.5, 0, 0.884422110552764],
       [0.8223495702005731, 0.5, 0, 0.8492462311557789],
       [0.9885386819484241, 0.5, 0, 0.507537688442211],
       [0.7507163323782234, 0.5, 0, 0.5427135678391961],
       [0.9255014326647564, 0.5, 0

In [115]:
# Task 3
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y=train_test_split(X,Y1)
import sklearn.linear_model as lm
model=lm.LogisticRegression()
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
pred_y=model.predict(test_x)


conf_mx = confusion_matrix(test_y, pred_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

array([[78,  0],
       [ 0, 72]], dtype=int64)

In [107]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='linear')
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='linear')

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       1.00      1.00      1.00        24

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

array([[74,  0],
       [ 0, 76]], dtype=int64)

In [119]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='poly' , degree= 100)
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(degree=100, kernel='poly')

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        22
           1       0.56      1.00      0.72        28

    accuracy                           0.56        50
   macro avg       0.28      0.50      0.36        50
weighted avg       0.31      0.56      0.40        50



C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Huraira Dogar\anaconda

array([[ 0, 78],
       [ 0, 72]], dtype=int64)

In [109]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='rbf')
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       1.00      1.00      1.00        24

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

array([[74,  0],
       [ 0, 76]], dtype=int64)

In [110]:
import sklearn.svm as sv
import sklearn.metrics as sm
model=sv.SVC(kernel='sigmoid')
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='sigmoid')

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       1.00      1.00      1.00        24

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\Huraira Dogar\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n

array([[74,  0],
       [ 0, 76]], dtype=int64)

In [112]:
import sklearn.tree as tr
import sklearn.metrics as sm
model=tr.ExtraTreeClassifier()
model.fit(train_x,train_y)
pred_y=model.predict(test_x)
print(sm.classification_report(test_y,pred_y))
import sklearn.model_selection as ms
from sklearn.metrics import confusion_matrix
y_train_pred = ms.cross_val_predict(model, train_x, train_y)
conf_mx = confusion_matrix(train_y, y_train_pred)
conf_mx

ExtraTreeClassifier()

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       1.00      1.00      1.00        24

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



array([1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0])

array([[74,  0],
       [ 0, 76]], dtype=int64)