In [1]:
l = list(range(1,100))
%time l2 = [x*2 for x in l]

Wall time: 0 ns


In [3]:
import numpy as np
a = np.arange(1,1000000)
%time a = a*2

Wall time: 7.76 ms


In [10]:
arr = np.zeros((2,2))
print(arr)

[[0. 0.]
 [0. 0.]]


In [11]:
arr = np.ones([2,2,2])
print(arr)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [17]:
arr = np.arange(5.1,5.9,0.1)
print(arr)
arr = arr.reshape(3,3)
print(arr)

[5.1 5.2 5.3 5.4 5.5 5.6 5.7 5.8 5.9]
[[5.1 5.2 5.3]
 [5.4 5.5 5.6]
 [5.7 5.8 5.9]]


In [23]:
arr = np.array([[[1,2,2]]])
np.shape(arr)

(1, 1, 3)