In [1]:
#task 1
import numpy as np
arr = np.random.randint(1,10,(10,2,2))
print(arr)

[[[9 1]
  [2 2]]

 [[1 3]
  [3 2]]

 [[9 8]
  [5 7]]

 [[4 3]
  [2 4]]

 [[4 1]
  [7 8]]

 [[5 3]
  [1 1]]

 [[7 7]
  [2 7]]

 [[4 7]
  [9 4]]

 [[4 6]
  [2 8]]

 [[6 3]
  [1 9]]]


In [37]:
#task 2
import numpy as np
arr = np.ones((5,5))
arr[1:2:2,:2:2]= 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
#task 3
arr = np.random.randint(1,10,(10,3,5))
arr[:,1,:] = 5
print(arr)

[[[1 9 9 7 6]
  [5 5 5 5 5]
  [8 9 7 2 3]]

 [[6 8 1 8 7]
  [5 5 5 5 5]
  [6 5 9 9 2]]

 [[6 4 5 1 4]
  [5 5 5 5 5]
  [9 9 8 4 2]]

 [[8 8 1 3 4]
  [5 5 5 5 5]
  [2 6 8 7 3]]

 [[9 2 5 2 5]
  [5 5 5 5 5]
  [5 2 3 7 5]]

 [[5 9 7 5 4]
  [5 5 5 5 5]
  [8 5 9 2 7]]

 [[3 9 4 6 8]
  [5 5 5 5 5]
  [7 1 8 8 2]]

 [[8 7 3 6 1]
  [5 5 5 5 5]
  [5 2 9 2 2]]

 [[4 7 6 6 7]
  [5 5 5 5 5]
  [6 6 8 4 3]]

 [[3 7 5 7 8]
  [5 5 5 5 5]
  [9 7 6 7 5]]]


In [34]:
#task 4
arr = np.random.randint(1,20,(3,3,3))
print(arr)
arr = np.where(arr%2 == 0,0,1)
print(arr)

[[[ 8  6 17]
  [15 10 12]
  [ 4 10 11]]

 [[18  7  5]
  [ 7 11 14]
  [ 9  8 13]]

 [[ 5 11  1]
  [13 14  6]
  [14 13  5]]]
[[[0 0 1]
  [1 0 0]
  [0 0 1]]

 [[0 1 1]
  [1 1 0]
  [1 0 1]]

 [[1 1 1]
  [1 0 0]
  [0 1 1]]]


In [48]:
#task 5
arr = np.zeros((4,3,2))
arr = arr.reshape((6,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [56]:
#task 6 (a)
%time list = [i for i in range(1,1001)]
%time arr = np.arange(1,1001)

#task 6 (b)
%time list = [i for i in range(1,100001)]
%time arr = np.arange(1,100001)

%time list = [i for i in range(1,1000001)]
%time arr = np.arange(1,1000001)

Wall time: 1.99 ms
Wall time: 0 ns
Wall time: 7.98 ms
Wall time: 0 ns
Wall time: 65.8 ms
Wall time: 0 ns
