In [ ]:
#Question 1
try:
    a=int(input())
    b=int(input())
except:
    print("you have enter invalid input")
    quit()
else:
    total = a + b
    print(total)


In [ ]:
#Question 2
try:
    number = int(input("Enter the number: "))
    exp = int(input("Enter its power: "))
except:
    print("Plz enter valid integar input")
else:
    print(pow(number,exp))
    print('Operation is successful')

In [ ]:
#Question 3
try:
    number = int(input("Enter the number: "))
    exp = int(input("Enter its power: "))
except:
    print("Plz enter valid integar input")
finally:
    #print(pow(number,exp))
    print('Operation is successful')

In [ ]:
#Question 4
def foo(arg):
    try:
        if (arg < 5):
            raise ValueError("Number is less than 5")
    except ValueError as ve:
        print(ve)
try:        
    foo()
except TypeError:
        print("Input Not Passed")

In [37]:
#task 1
import numpy as np
arr = np.random.randint(1,9,(5,3,7,4,3))


# print(arr)

#l1 =arr[0][2:5][0][3:6]
print(arr[0][2:5][0][3:6])
#print(l1)

[[[8 3 5]
  [6 1 4]
  [6 5 4]
  [4 8 6]]

 [[8 2 3]
  [4 5 5]
  [8 4 6]
  [7 2 5]]

 [[4 1 5]
  [1 1 5]
  [6 2 1]
  [8 8 7]]]


In [21]:
#task 1
import numpy as np
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a*b)
print(a-b)
print(b/a)
print(a+b)
print(b//a)

[ 5 12 21 32]
[-4 -4 -4 -4]
[5.         3.         2.33333333 2.        ]
[ 6  8 10 12]
[5 3 2 2]


In [39]:
#task 2
a = np.array([1,2,3,4])
b = np.arange(1,5)
c = np.zeros((2,2,3))
d = np.ones((3,2))
e = np.empty([4,2])
f = np.full([3,2],10)
j = np.eye(3,3)
k = np.linspace(0, 10, num=4)
print(a,b)
print(c)
print(d)
print(e)
print(f)
print(j)
print(k)

[1 2 3 4] [1 2 3 4]
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000]
 [0.00e+000 4.96e-321]
 [0.00e+000 0.00e+000]]
[[10 10]
 [10 10]
 [10 10]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0.          3.33333333  6.66666667 10.        ]


In [67]:
#task 3
arr = np.arange(1,19)
arr = np.reshape(arr,[2,3,3])
print(arr[1,[2]])
print(arr[0][0:2])

[[16 17 18]]
[[1 2 3]
 [4 5 6]]


In [109]:
#task 4
print(np.abs(-44))
print(np.fabs(-44))
print(np.sqrt(24))
print(np.exp(1))
print(np.abs(-44))
print(np.log(99))
print(np.log10(99))
print(np.log2(99))
print(np.log1p(99))
print(np.ceil(4.4))
print(np.floor(4.4))
print(np.rint(4.9))
print(np.modf([1.2,3.44,4.44,12.33]))
print(np.isnan([1,2,3,np.nan]))
print(np.isfinite(1))
print(np.inf)
print(np.cos(60))
print(np.cosh(60))
print(np.sin(60))
print(np.sinh(60))
print(np.tan(90))
print(np.tanh(90))
#print(np.arccos(10))
print(np.arccosh(60))
#print(np.arcsin(10))
print(np.arcsinh(60))
print(np.arctan(90))
#print(np.arctanh(20))
print(np.logical_not([0,2,3,4]))



44
44.0
4.898979485566356
2.718281828459045
44
4.59511985013459
1.99563519459755
6.6293566200796095
4.605170185988092
5.0
4.0
5.0
(array([0.2 , 0.44, 0.44, 0.33]), array([ 1.,  3.,  4., 12.]))
[False False False  True]
True
inf
-0.9524129804151563
5.710036949078421e+25
-0.3048106211022167
5.710036949078421e+25
-1.995200412208242
1.0
4.787422291102689
4.78756117999381
1.5596856728972892
[ True False False False]


In [124]:
#task 5
print(np.add([1,2,3,4],[5,6,7,8]))
print(np.subtract([1,2,3,4],[5,6,7,8]))
print(np.multiply([1,2,3,4],[5,6,7,8]))
print(np.divide([1,2,3,4],[5,6,7,8]))
print(np.floor_divide([5,6,7,8],[1,2,3,4]))
print(np.power([5,6,7,8],[1,2,3,4]))
print(np.fmax([5,6,7,8],[1,2,3,4]))
print(np.fmin([5,6,0,3],[1,2,3,4]))
print(np.mod([10,29,10,19],[1,2,3,4]))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[5 3 2 2]
[   5   36  343 4096]
[5 6 7 8]
[1 2 0 3]
[0 1 1 3]


In [133]:
#task 6
arr = np.random.randint(1,10,(2,4))
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

40
5.0
2.0615528128088303
4.25
1
7
0
1
[ 1  8 15 20 26 29 36 40]
[     1      7     49    245   1470   4410  30870 123480]


In [9]:
#task 7
import numpy as np
arr = np.random.randint(1,10,(2,4))
print(np.unique(arr))
print(np.intersect1d([1,2,3,4],[2,3,4]))
print(np.union1d([1,2,3,4],[3,4,5]))
print(np.in1d([1,2,34],[3,4,5,1]))
print(np.setdiff1d([1,2,3,4],[2,3,4]))
print(np.setxor1d([1,5,7,8],[1,2,3,4,5]))

[2 3 4 5 6 9]
[2 3 4]
[1 2 3 4 5]
[ True False False]
[1]
[2 3 4 7 8]
